### ISSUE TITLE
Persistence across boxes

### ISSUE THREAD

**Issue by bergen** [oakes/paren-soup#13]
Thanks for developing this library! I'm using it to develop a computational linguistics [course](https://bergen.github.io/foundations-computational-linguistics/Lecture1) at UCSD, and it's a really useful tool.

Is there a way to make variable definitions persist across code boxes? It would be useful to be able to define a variable in a box earlier in the page, and then use the definition in a later box.

**Comment by oakes** [comment]
That is really neat! The reason defs don't work across code boxes is, each one is getting their own isolated web worker to run eval. However, you piqued my interest so I just released a new version that optionally runs the compiler directly in the DOM, rather than in a web worker, so each code box shares the same compiler. Try downloading [the latest version](https://github.com/oakes/paren-soup/releases/tag/2.12.0) and make your HTML include "paren-soup-with-compiler.js" rather than "paren-soup.js" and, theoretically, it will work! Let me know if it doesn't and I'll see if i messed something up.

**Comment by bergen** [comment]
Thanks, I'll let you know how this goes!

**Comment by bergen** [comment]
This works, thank you!

**Comment by oakes** [comment]
Awesome, I'll close this then
