### ISSUE TITLE
How might I safely use paren-soup inside a React app?

### ISSUE THREAD

**Issue by robert-stuttaford** [oakes/paren-soup#8]
I'm not sure how to safely update the contents of the editor from 'outside'.

I found <https://github.com/lovasoa/react-contenteditable/blob/master/src/react-contenteditable.js> but I'm not quite sure how to reconcile the behaviour there with what paren-soup is doing.

**Comment by oakes** [comment]
Nightlight is actually a reagent app that uses paren-soup. However, I don't
modify the editor contents from reagent; I'm pretty sure react does not
play well with contenteditable elements in general.

On Jul 30, 2017 6:24 AM, "Robert Stuttaford" <notifications@github.com>
wrote:

I'm not sure how to safely update the contents of the editor from 'outside'.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/oakes/paren-soup/issues/8>, or mute the thread

**Comment by robert-stuttaford** [comment]
Thanks! 

A quick glance at <https://github.com/oakes/Nightlight/blob/master/src/cljs/nightlight/editors.cljs> suggests a way forward. 

Thanks for such a wonderful contribution to the community!

**Comment by oakes** [comment]
Let me know if you need any more help with this, I'll be happy to do so.
